# Site settings
title: Xin Liu
description: Xin Liu. Researcher @Supcon. PhD @Tsinghua University.
url: https://liuxin.github.io
# baseurl: "/particle" # the subpath of your site, e.g. /blog

timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass

# User settings
username: Xin Liu
user_title: Researcher
user_description: >
  I am a researcher at <a href="https://www.supcon.com/" target="_blank">Supcon</a>. 
  I received my Ph.D. from 
  <a href="https://www.tsinghua.edu.cn/" target="_blank">Tsinghua University</a> 
  in 2025, advised by <a href="https://iiis.tsinghua.edu.cn/rydw/qzjs/xuwei.htm" target="_blank">Prof. Wei Xu</a>. 
  My research interests include graph foundation models, hypergraph, large language models, ontology,  
  multi-party computation, graph algorithms, graph neural networks, and fraud detection.
email: liuxin@mails.tsinghua.edu.cn
avatar: /photo.jpg
# twitter: 
github: liuxin
scholar: https://scholar.google.com/citations?hl=en&user=AWSswSgAAAAJ
openreview: https://openreview.net/profile?id=%7EXin_Liu31
# facebook: 
# gplus_username:  
