# Site settings
title: Xin Liu
description: Xin Liu. Researcher @Supcon. PhD @Tsinghua University.
url: https://liuxin.github.io
# baseurl: "/particle" # the subpath of your site, e.g. /blog

timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass

# User settings
username: Xin Liu
user_title: Researcher
user_description: >
  HI! I am a researcher at <a href="https://www.supcon.com/" target="_blank">Supcon</a> working on enterprise intelligence where our team is aiming to build enterprise-grade intelligent systems that encapsulate enterprise knowledge, business entities, and operational logic, enabling structured reasoning and task planning while preserving explainability and execution determinism.
  
  My research work mainly focuses on using (hyper-)graph, ontology and large language models (LLMs) in achieving the team's goals, with a focus on retrieval-augmented generation (RAG) methods and graph foundation models.
  
  I received my Ph.D. from <a href="https://www.tsinghua.edu.cn/" target="_blank">Tsinghua University</a> in 2025, advised by <a href="https://iiis.tsinghua.edu.cn/rydw/qzjs/xuwei.htm" target="_blank">Prof. Wei Xu</a>, where I worked on fraud detection, multi-party computation, graph algorithms, and graph neural networks. The pursuit of my Ph.D. degree was greatly supported by my advisor Prof. Wei Xu and many others including my friends and family ❤️.
  
  Please feel free to contact me! <a href="mailto:liuxin4@supcon.com">liuxin4@supcon.com</a>; <a href="mailto:greenliuxin@163.com">greenliuxin@163.com</a>
email: liuxin4@supcon.com
avatar: /photo.jpg
# twitter: 
github: liuxin
scholar: https://scholar.google.com/citations?hl=en&user=AWSswSgAAAAJ
openreview: https://openreview.net/profile?id=%7EXin_Liu31
# facebook: 
# gplus_username:  
